export type GolfCourse = {
  carrier: number;
  golfCourseId: number;
  golfCourseName: string;
  golfCourseAbbr: string;
  golfCourseNameKana: string;
  golfCourseCaption: string;
  information: string;
  highway: string;
  ic: string;
  icDistance: string;
  latitude: number;
  longitude: number;
  postalCode: string;
  address: string;
  telephoneNo: string;
  faxNo: string;
  openDay: string;
  closeDay: string;
  creditCard: string;
  shoes: string;
  dressCode: string;
  practiceFacility: string;
  course: string;
  holeCount: number;
  parCount: number;
  courseDistance: string;
  green: string;
  greenCount: number;
  longDrivingContest: string;
  nearPin: string;
  ratingNum: number;
  evaluation: number;
  staff: number;
  facility: number;
  meal: number;
  costperformance: number;
  distance: number;
  fairway: number;
  reserveCalUrl: string;
  voiceUrl: string;
  layoutUrl: string;
  routeMapUrl: string;
  newPlans: string | null;
  ratings: string | null;
};
